### PR TITLE
Support for process details in eBPF events

### PR DESCRIPTION
**Pull request by slashben**

### CODE REVIEW

**Review by amitschendel — CHANGES_REQUESTED** [review]
Looks good!
Notice you need to add decode and encode functions for process details in events.go.

**Comment by slashben** [comment]
> Looks good! Notice you need to add decode and encode functions for process details in events.go.

Actually, we need to remove them. We don't need them anymore (since we moved away from `boltdb`/`nutdb`)

**Comment by amitschendel** [comment]
Oh right, I forgot about it.
Remove then and I will approve.

**Comment by slashben** [comment]
> Oh right, I forgot about it. Remove then and I will approve.

done

**Review by amitschendel — APPROVED** [review]
GJ :)

**Pull request merged**
